### ISSUE TITLE
Source files

### ISSUE THREAD

**Issue by MichaelMartinez** [jiannazzone/Gridfinity-Small-Parts#1]
Thank you for posting the files for your box. Are you going to release the source files? I would help create different sized thicknesses for the wood panels. I can also create some finger joints for CNC manufacture. Further ideas include a 3d printed locking/stacking mechanism similar to packout and other modular toolboxes.

**Comment by jiannazzone** [comment]
Ask, and you shall receive! Added in commit [74540a4](https://github.com/jiannazzone/Gridfinity-Small-Parts/commit/74540a40bfa90c48f20a032ab1b8dd57587efe5d)
